### ISSUE TITLE
MacOS not building properly

### ISSUE THREAD

**Issue by MasonT8198** [codedwrench/xlinkhandheldassistant#30]
**Describe the bug**
Created Mostly for Tracking, however I couldn't get XLHA to build properly on my mac

**Devices**
Can test with PSP, and/or Vita

**Versions**
N/A

**To Reproduce**
Run the brew command to install the packages
`brew install cmake gcc@10 boost ncurses libpcap libpthread-stubs`
this may not be all the packages needed but it failed during the cmake portion before even trying to compile

**Expected behavior**
XLHA should build and run correctly on MacOS

**Desktop:**
- OS/Distro: MacOS Monterey

Specs:

iMac (Retina 5K, 27-inch, 2019)
CPU - 3.7 GHz 6-Core Intel Core i5
RAM - 8 GB 2667 MHz DDR4
GPU - Radeon Pro 580X 8 GB

**Comment by MasonT8198** [comment]
This may be just due to me doing something wrong, I will be continuing to debug however to see if I can get this to build properly.

**Comment by MasonT8198** [comment]
edit: after installing the libraries that *should be needed* 
```
CMake Error at /usr/local/Cellar/cmake/3.22.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PCAP (missing: PCAP_LIBRARY PCAP_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPCAP.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:108 (find_package)
```

**Comment by MasonT8198** [comment]
[CMakeError.log](https://github.com/codedwrench/xlinkhandheldassistant/files/7678455/CMakeError.log)
[CMakeOutput.log](https://github.com/codedwrench/xlinkhandheldassistant/files/7678456/CMakeOutput.log)

**Comment by codedwrench** [comment]
Try now

**Comment by MasonT8198** [comment]
Works perfectly fine with dynamic linking and a disabled amfi.
