### ISSUE TITLE
one network adapter with 2 or more psp/psv Device support

### ISSUE THREAD

**Issue by lightfirst** [codedwrench/xlinkhandheldassistant#44]
tested psp games
even xlink kai found consoles have 2 playstation handheld, I didn't make that work

**Comment by codedwrench** [comment]
vita should already work with this, an addition to the plugin to make this work is currently in progress, it should work for most, but not all games after this improvement is implemented

**Comment by codedwrench** [comment]
update: my plugin change did not help fully, i need to add something that sens out the traffic unmodified again from the pc side only when specifically enabled
