### ISSUE TITLE
Compiling.md: Boost Issues after build overhaul on Arch

### ISSUE THREAD

**Issue by MasonT8198** [codedwrench/xlinkhandheldassistant#49]
Installing boost from pacman using `pacman -S boost boost-libs` causes boost to not be found using the command listed in the doc "mkdir build && cd build && cmake .. && cmake --build . -- -j`nproc`"

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) (Required
  is at least version "1.71")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindBoost.cmake:2375 (find_package_handle_standard_args)
  cmake/wrapfindboost.cmake:39 (find_package)
  CMakeLists.txt:137 (include)

**Comment by MasonT8198** [comment]
I assume this is due to the way compilation works now, also a note that you have to get ncurses5-compat-libs and libpthread-stubs from the AUR is probably a good mention.

**Comment by codedwrench** [comment]
ncurses5-compat-libs and libpthread-stubs are not needed on arch.
just having ncurses is sufficient
